/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as CryptoIndexImport } from './routes/crypto/index'
import { Route as CryptoCoinIdImport } from './routes/crypto/$coinId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CryptoIndexRoute = CryptoIndexImport.update({
  id: '/crypto/',
  path: '/crypto/',
  getParentRoute: () => rootRoute,
} as any)

const CryptoCoinIdRoute = CryptoCoinIdImport.update({
  id: '/crypto/$coinId',
  path: '/crypto/$coinId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/crypto/$coinId': {
      id: '/crypto/$coinId'
      path: '/crypto/$coinId'
      fullPath: '/crypto/$coinId'
      preLoaderRoute: typeof CryptoCoinIdImport
      parentRoute: typeof rootRoute
    }
    '/crypto/': {
      id: '/crypto/'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crypto/$coinId': typeof CryptoCoinIdRoute
  '/crypto': typeof CryptoIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crypto/$coinId': typeof CryptoCoinIdRoute
  '/crypto': typeof CryptoIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crypto/$coinId': typeof CryptoCoinIdRoute
  '/crypto/': typeof CryptoIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/crypto/$coinId' | '/crypto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/crypto/$coinId' | '/crypto'
  id: '__root__' | '/' | '/about' | '/crypto/$coinId' | '/crypto/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CryptoCoinIdRoute: typeof CryptoCoinIdRoute
  CryptoIndexRoute: typeof CryptoIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CryptoCoinIdRoute: CryptoCoinIdRoute,
  CryptoIndexRoute: CryptoIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/crypto/$coinId",
        "/crypto/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/crypto/$coinId": {
      "filePath": "crypto/$coinId.tsx"
    },
    "/crypto/": {
      "filePath": "crypto/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
